### ISSUE TITLE
It doesn't compile under windows

### ISSUE THREAD

**Issue by Hemiun** [go-ap/storage-fs#1]
Hi, guys. There is a trouble with compilation storage-fs under windows 10: 
`.\repository.go:230:32: undefined: syscall.Stat_t`
Becouse syscall for windows doesn't contained stat_t struct/ 
I suppose place func isHardLink into separate files (one for windows and one for linux) with instruction // +build <os>
Implementation for windows should be different. For example, it is possible to use **syscall.GetFileInformationByHandle**

**Comment by mariusor** [comment]
Personally I don't really think it's feasible to use this on Windows. 

However the functionality of `isHardlink` is not essential for the use of the library so I can remove it.

My advice would be to use one of the other storage backends if possible. I can't tell you more because you didn't give any information about what your use case is.
